### Frontend build + static serve via nginx
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

# copy all files and build
COPY . .
RUN npm run build

FROM nginx:alpine
# Remove default nginx content
RUN rm -rf /usr/share/nginx/html/*

# Copy built frontend into nginx
# Angular build outputs into /app/dist/<project-name> (see angular.json)
## Copy 'browser' subfolder generated by Angular to nginx root
COPY --from=build /app/dist/payment-system-angular/browser/ /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
